export const SET_PLAYERS_VALUE = 'SET_PLAYERS_VALUE';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_HEIGHT = 'SET_HEIGHT';
export const SET_CURRENT_PLAYER = 'SET_CURRENT_PLAYER';
export const SET_PLAYERS_ARRAY = 'SET_PLAYERS_ARRAY';
export const SET_PLAYERS_CURRENT_ARRAY = 'SET_PLAYERS_CURRENT_ARRAY';
export const SET_WINNER = 'SET_WINNER';