export const SET_PLAYERS_VALUE = 'SET_PLAYERS_VALUE';
export const SET_WIDTH = 'SET_WIDTH';
export const SET_HEIGHT = 'SET_HEIGHT';
export const SET_ACTIVE_PLAYER = 'SET_ACTIVE_PLAYER';
export const SET_PLAYERS_ARRAY = 'SET_PLAYERS_ARRAY';
export const SET_CURRENT_PLAYERS = 'SET_CURRENT_PLAYERS';
export const SET_WINNER = 'SET_WINNER';